# Generated by Django 6.0.3 on 2026-05-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_alter_customer_id_alter_feedback_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Pending', 'ຮັບອໍເດີແລ້ວ'), ('Shipping', 'ກຳລັງຈັດສົ່ງ'), ('Completed', 'ຈັດສົ່ງສຳເລັດ')], max_length=50, null=True),
        ),
    ]
