# Generated by Django 6.0.3 on 2026-05-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Pending', 'ຮັບອໍເດີ'), ('Processing', 'ກຳລັງຈັດສົ່ງ'), ('Delivered', 'ຈັດສົ່ງສຳເລັດ')], max_length=50, null=True),
        ),
    ]
