# Generated by Django 6.0.3 on 2026-06-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0010_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_group',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
