# Generated by Django 6.0.3 on 2026-06-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0011_orders_order_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Pending', 'ຮັບອໍເດີ'), ('Processing', 'ກຳລັງຈັດສົ່ງ'), ('Delivered', 'ຈັດສົ່ງສຳເລັດ'), ('Cancelled', 'ຍົກເລີກ')], default='Pending', max_length=50, null=True),
        ),
    ]
