# Generated by Django 6.0.3 on 2026-06-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0012_alter_orders_order_date_alter_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='delivery_km',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='delivery_type',
            field=models.CharField(blank=True, default='Delivery', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(blank=True, default='COD', max_length=20, null=True),
        ),
    ]
