# Generated by Django 6.0.3 on 2026-06-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0013_orders_delivery_fee_orders_delivery_km_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Pending', 'ລໍຖ້າການຢືນຢັນ'), ('Confirmed', 'ຮັບ/ຢືນຢັນອໍເດີ'), ('Processing', 'ກຳລັງຈັດສົ່ງ'), ('Delivered', 'ຈັດສົ່ງສຳເລັດ'), ('Cancelled', 'ຍົກເລີກ')], default='Pending', max_length=50, null=True),
        ),
    ]
