# Generated by Django 6.0.3 on 2026-06-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0014_alter_orders_status_add_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('ຈອກ', 'ຈອກ'), ('ທໍ່ດູດ', 'ທໍ່ດູດ'), ('ໝາກໄມ້ສົດ', 'ໝາກໄມ້ສົດ'), ('ນ້ຳກ້ອນ', 'ນ້ຳກ້ອນ'), ('ນົມ', 'ນົມ'), ('ນ້ຳຕານ', 'ນ້ຳຕານ'), ('ຖົງ/ບັນຈຸ', 'ຖົງ/ບັນຈຸ'), ('ຜັກ/ສ່ວນປຸ່ງ', 'ຜັກ/ສ່ວນປຸ່ງ'), ('ນ້ຳ/ວັດຖຸດິບ', 'ນ້ຳ/ວັດຖຸດິບ'), ('ອຸປະກອນຮ້ານ', 'ອຸປະກອນຮ້ານ'), ('ຄ່າໄຟ/ນ້ຳ', 'ຄ່າໄຟ/ນ້ຳ'), ('ອື່ນໆ', 'ອື່ນໆ')], default='ອື່ນໆ', max_length=30)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('amount', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
