# Generated by Django 6.0.3 on 2026-07-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0017_product_is_available_customorderrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorderrequest',
            name='order_group',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
