# Generated by Django 6.0.3 on 2026-07-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0018_customorderrequest_order_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('closed', 'ປິດຮ້ານ'), ('promo', 'ໂປໂມຊັ່ນ')], default='promo', max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('message', models.CharField(blank=True, default='', max_length=300)),
                ('icon', models.CharField(blank=True, default='📢', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
