# Generated by Django 6.0.3 on 2026-07-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0019_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(default='ອື່ນໆ', max_length=30),
        ),
    ]
