# Generated by Django 6.0.3 on 2026-07-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0020_alter_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
