# Generated by Django 6.0.3 on 2026-07-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0021_orders_pickup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
