# Generated by Django 6.0.3 on 2026-07-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0022_orders_pickup_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
