# Generated by Django 6.0.3 on 2026-07-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0027_subcategory_product_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit_percent', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
            ],
        ),
    ]
