# Generated by Django 6.0.3 on 2026-07-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0028_financesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='deposit_verified',
            field=models.BooleanField(default=False),
        ),
    ]
