# Generated by Django 6.0.3 on 2026-07-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0029_orders_deposit_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='color',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
