"""
Django settings for ecommerce project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATE_DIR = os.path.join(BASE_DIR,'templates')
STATIC_DIR=os.path.join(BASE_DIR,'static')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '#vw(03o=(9kbvg!&2d5i!2$_58x@_-3l4wujpow6(ym37jxnza'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['webvilla-production.up.railway.app', '127.0.0.1', 'localhost']

CSRF_TRUSTED_ORIGINS = [
    'https://webvilla-production.up.railway.app',
]

# Application definition

INSTALLED_APPS = [
    'simpleui', # <---- HERE
    'django.contrib.admin',
    'webpush',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ecom',
    'widget_tweaks',

]

# ຕັ້ງຄ່າ Webpush — ໃຊ້ສົ່ງແຈ້ງເຕືອນສະຖານະອໍເດີຫາລູກຄ້າ (ບໍ່ຕ້ອງເສຍຄ່າບໍລິການ)
WEBPUSH_SETTINGS = {
    "VAPID_PUBLIC_KEY": "BATXUpDWQlUtoqH9HrPbDN0uRtEmP4WeZrWazcBg3AZc5XmmSEi3yoo2CUzeyTD7BlFmTU6-IJC_Lqv09Zc86XA",
    "VAPID_PRIVATE_KEY": "Y37H1k5gfHNMbp_ZpeI5awRyoH8SqhQIteZQ1_0Uohs",
    "VAPID_ADMIN_EMAIL": "admin@villasmoothie.com"
}

# ── Twilio SMS ──────────────────────────────────────────────────
# ຄັດລອກຈາກ https://console.twilio.com
TWILIO_ACCOUNT_SID  = 'ACxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'   # ໃສ່ SID ຂອງທ່ານ
TWILIO_AUTH_TOKEN   = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'     # ໃສ່ Auth Token ຂອງທ່ານ
TWILIO_FROM_NUMBER  = '+1XXXXXXXXXX'                         # ໃສ່ Twilio phone number ຂອງທ່ານ

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # ຕື່ມແຖວນີ້ເຂົ້າໄປ
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR,],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                 'ecom.context_processors.cart_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases
#
# Uses a real Postgres database (persists across deploys/restarts) when
# DATABASE_URL is set — e.g. Railway sets this automatically once a
# PostgreSQL service is added and linked to this app. Falls back to the
# local SQLite file for local development only (SQLite on Railway is NOT
# persistent: it gets reset to whatever was last committed to git on every
# deploy, which silently wiped real customer/order data in the past).

import dj_database_url

DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Lets customers log in with the phone number they signed up with, in addition
# to their auto-generated username (see ecom/auth_backends.py).
AUTHENTICATION_BACKENDS = [
    'ecom.auth_backends.MobileOrUsernameBackend',
    'django.contrib.auth.backends.ModelBackend',
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Bangkok'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


STATICFILES_DIRS=[STATIC_DIR,]

MEDIA_URL  = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'static')

LOGIN_REDIRECT_URL='/afterlogin'

LOGOUT_REDIRECT_URL = '/'  # ຫຼັງຈາກອອກລະບົບ ໃຫ້ກັບມາໜ້າ Login

SESSION_SAVE_EVERY_REQUEST = True

#for contact us give your gmail id and password
EMAIL_BACKEND ='django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'from@gmail.com' # this email will be used to send emails
EMAIL_HOST_PASSWORD = 'xyz' # host email password required
# now sign in with your host gmail account in your browser
# open following link and turn it ON
# https://myaccount.google.com/lesssecureapps
# otherwise you will get SMTPAuthenticationError at /contactus
# this process is required because google blocks apps authentication by default
EMAIL_RECEIVING_USER = ['to@gmail.com'] # email on which you will receive messages sent from website
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
